name: CI

run-name: "CI – ${{ github.ref_name }} (${{ github.actor }})"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: read
  pages: write

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Unit tests
        run: yarn test
      - name: Publish unit test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit test results
          path: '**/reports/**/*.xml'
          reporter: java-junit
          list-suites: 'all'
          list-tests: 'failed'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Build
        run: yarn build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: public/

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: yarn
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: public/
      - name: Integration tests
        run: yarn test:e2e
      - name: Publish integration test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Integration test results
          path: '**/reports/**/*.xml'
          reporter: java-junit
          list-suites: 'all'
          list-tests: 'failed'

